In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
a = [2, 5, 0]
b = [6, 0, 7]
c = [5, 11, 7]

In [3]:
m = np.array([a, b, c])
print(m)

[[ 2  5  0]
 [ 6  0  7]
 [ 5 11  7]]


In [4]:
mT = np.transpose(m)
print(mT)

[[ 2  6  5]
 [ 5  0 11]
 [ 0  7  7]]


In [5]:
det_m = la.det(m)
print(det_m)

-189.00000000000003


In [6]:
alt_det_m = -119

mInv = np.dot((1/det_m), mT) # this isn't exactly supposed to be the transpose


print(mInv)

[[-0.01058201 -0.03174603 -0.02645503]
 [-0.02645503  0.         -0.05820106]
 [ 0.         -0.03703704 -0.03703704]]


In [7]:
np.matmul(m,mInv)

array([[-0.15343915, -0.06349206, -0.34391534],
       [-0.06349206, -0.44973545, -0.41798942],
       [-0.34391534, -0.41798942, -1.03174603]])

# Hill Cypher: encryption (multiply matrix x vector)

In [8]:
d = [5, 6]
e = [-2, -3]

m2 = np.array([d, e])


#inv only -- run bottom cells before this
m2 = mInv3.copy()

print(m2)

NameError: name 'mInv3' is not defined

In [9]:
top = [24]
btm = [1]

vct = np.array([top, btm])
print(vct)

[[24]
 [ 1]]


In [10]:
new_vct = np.matmul(m2, vct)
print(new_vct)

[[126]
 [-51]]


In [11]:
alph_vct = np.array([[-1],[-1]])

for i in range(len(new_vct)):
    alph_vct[i][0] = int(new_vct[i][0].copy()) % 26
print(alph_vct)

[[22]
 [ 1]]


# Hill Cypher: decryption

# Invert 2x2 Matrix

In [ ]:
f = [5, 6]
g = [-2, -3]

m3 = np.matrix([f, g])

print(m3)

In [ ]:
#find det of m3

det_m3 = la.det(m3)
#print(det)

#create special matrix -- matrix used for finding the inverse matrix
m3_Spc = m3.copy()
m3_Spc[0,0] = m3[1,1] #flip a and d
m3_Spc[1, 1] = m3[0, 0]
m3_Spc[0,1] = -m3_Spc[0, 1] #make b and c negative
m3_Spc[1, 0] = -m3_Spc[1, 0]

#m3_Spc[:, :]

#make inverse matrix

mInv3 = np.dot((1/det_m3), m3_Spc)


#print matrix, inverse, and product
#print(m3)
print(mInv3)
np.matmul(mInv3, m3)

# Fast Modular Exponentiation

In [12]:
import math

params = [372, 15, 821] #base, power, modulus

base = params[0]
power = params[1]
modulus = params[2]

modular_equivalents = [] #these are the modular equivalents of powers of the base

max_pow_2chk = 1

while max_pow_2chk < power :
    modular_equivalents.append(pow(base, max_pow_2chk) % modulus)
    max_pow_2chk = max_pow_2chk * 2
    
if max_pow_2chk > power :
    print("The highest power of " + str(base) + " neccesary to represent " + str(base) + "^" + str(power) + " is " + str(max_pow_2chk/2))


max_pow = max_pow_2chk/2
max_pow_copy = max_pow

coef_4_binary_expand = [] #the zero-th coeficcient corresponds to the largest power in the decomposition

answer = -1 #default for error detection

sum_pows_of_bases = 0

solution = ""

while max_pow_copy >= 1 and sum_pows_of_bases != power:
    index_of_power = int(math.log(max_pow_copy, 2)) #this index of power can also be thought of as how many doublings the current max_pow_copy represents
    if answer == -1:
        answer = modular_equivalents[index_of_power]
        sum_pows_of_bases = max_pow_copy
        solution = str(base) + "^" + str(max_pow_copy)
    
    if power - sum_pows_of_bases - max_pow_copy >= 0:
        if answer != -1:
            answer = answer * modular_equivalents[index_of_power] % modulus
            sum_pows_of_bases += max_pow_copy
            solution = solution + " * " + str(base) + "^" + str(max_pow_copy)
    max_pow_copy = max_pow_copy / 2
    
    

    
high_rmndr = modular_equivalents[int(math.log(max_pow, 2))]

#print("The remainder of the highest power, smaller than " + str(power) + ", moduluo " + str(power) + ", is " + str(high_rmndr))

answer = str(answer)

print("The answer is: " + answer + " (mod " + str(modulus) + ") ")
#print(solution + " (mod "+ str(power) +")")

The highest power of 372 neccesary to represent 372^15 is 8.0
The answer is: 183 (mod 821) 


In [13]:
452 * 183 % 821

616

In [16]:
import math_n_crypto_functions as cryp
import easygui

cryp.find_mlt_inv()

ModuleNotFoundError: No module named 'easygui'

In [ ]:
628/38

In [ ]:
448/2

In [ ]:
pow(int(answer), 17) % 67

In [ ]:
modular_equivalents

In [ ]:
32 + 8 + 4 + 1